name: uniride_app
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Google Maps
  google_maps_flutter: ^2.5.1

  # Firebase packages 
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  firebase_messaging: ^16.0.4

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Location package
  geolocator: ^14.0.2

  # Autocomplete / HTTP requests
  http: ^1.2.0

  # Date formatting
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook: ^3.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/uniride_logo.jpg
